# Generated by Django 5.1.1 on 2024-10-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
